### PR TITLE
feat: add fraction xerc20

### PR DESCRIPTION
**Pull request by just-a-node**

### CODE REVIEW

**Comment by just-a-node** [comment]
@pjenviri Can you help and see why inputting any value of FRACTION < `0.001` is giving a BigNumber error?

```
Error: invalid decimal value (argument="value", value="5e-7"
```

**Comment by pjenviri** [comment]
it is fixed in this commit: https://github.com/CoinHippo-Labs/connext-bridge/pull/218/commits/38c95f14ded42cd5afef5cad38ec22d3d76650ab

**Comment by pjenviri** [comment]
@just-a-node , should we merge this pr?

**Comment by just-a-node** [comment]
> @just-a-node , should we merge this pr?

Was testing, we are ready to merge.

**Review by pjenviri — APPROVED** [review]

**Pull request merged**
